//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Thu Mar 23 2017 17:03:47
//
//      Input file      : 
//      Component name  : addressgroup
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module addressgroup(clk, address_in, address_out, ic_out, sel_source, inc, load_ic, reset_ic);
   input         clk;
   
   input [31:0]  address_in;
   
   output [31:0] address_out;
   output [31:0] ic_out;
   
   input         sel_source;
   input         inc;
   input         load_ic;
   input         reset_ic;
   
   
   wire [31:0]   instruction;
   
   
   instructioncounter ic(.clk(clk), .load(load_ic), .inc(inc), .reset(reset_ic), .data_in(address_in), .data_out(instruction));
   
   
   multiplexer2 #(32) mux(.selector(sel_source), .data_in_0(instruction), .data_in_1(address_in), .data_out(address_out));
   
   assign ic_out = instruction;
   
endmodule
