//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Thu Mar 23 2017 17:04:14
//
//      Input file      : 
//      Component name  : flaggroup
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module flaggroup(clk, c_in, z_in, c_out, z_out, load_c, load_z, sel_c, sel_z);
   input       clk;
   
   input       c_in;
   input       z_in;
   
   output      c_out;
   output      z_out;
   
   input       load_c;
   input       load_z;
   input [1:0] sel_c;
   input [1:0] sel_z;
   
   
   wire        mux_to_c;
   wire        mux_to_z;
   
   
   flag carry_flag(.clk(clk), .load(load_c), .data_in(mux_to_c), .data_out(c_out));
   
   
   flag zero_flag(.clk(clk), .load(load_z), .data_in(mux_to_z), .data_out(z_out));
   
   
   multiplexer4 #(1) carry_mux(.selector(sel_c), .data_in_00(c_in), .data_in_01(1'bx), .data_in_10(1'b0), .data_in_11(1'b1), .data_out(mux_to_c));
   
   
   multiplexer4 #(1) zero_mux(.selector(sel_z), .data_in_00(z_in), .data_in_01(1'bx), .data_in_10(1'b0), .data_in_11(1'b1), .data_out(mux_to_z));
   
endmodule
