//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Thu Mar 23 2017 17:04:23
//
//      Input file      : 
//      Component name  : registergroup
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module registergroup(clk, result_in, vector_in, ic_in, enable_in, x_out, y_out, a_out, sel_source, sel_dest);
   input         clk;
   
   input [31:0]  result_in;
   input [31:0]  vector_in;
   input [31:0]  ic_in;
   input         enable_in;
   
   output [31:0] x_out;
   output [31:0] y_out;
   output [31:0] a_out;
   
   input [1:0]   sel_source;
   input [1:0]   sel_dest;
   
   
   wire [31:0]   data_in;
   wire          load_x;
   wire          load_y;
   wire          load_a;
   
   
   multiplexer4 #(32) mux_input(.selector(sel_source), .data_in_00(result_in), .data_in_01(ic_in), .data_in_10(vector_in), .data_in_11(32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx), .data_out(data_in));
   
   
   demultiplexer1x4 demux(.selector(sel_dest), .data_in(enable_in), .data_out_00(), .data_out_01(load_a), .data_out_10(load_x), .data_out_11(load_y));
   
   
   dataregister reg_x(.clk(clk), .load(load_x), .data_in(data_in), .data_out(x_out));
   
   
   dataregister reg_y(.clk(clk), .load(load_y), .data_in(data_in), .data_out(y_out));
   
   
   dataregister reg_a(.clk(clk), .load(load_a), .data_in(data_in), .data_out(a_out));
   
endmodule
