//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Thu Mar 23 2017 17:05:25
//
//      Input file      : 
//      Component name  : dataregister
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module dataregister(clk, load, data_in, data_out);
   input         clk;
   input         load;
   input [31:0]  data_in;
   output [31:0] data_out;
   
   reg [4:0]     data_out_buffer;
   
   always
   begin
      @(posedge clk);
      
      if (load == 1'b1)
         data_out_buffer <= data_in;
      else
         data_out_buffer <= data_out_buffer;
   end
   
   assign data_out = data_out_buffer;
   
endmodule
