//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Thu Mar 23 2017 17:05:36
//
//      Input file      : 
//      Component name  : demultiplexer1x4
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module demultiplexer1x4(selector, data_in, data_out_00, data_out_01, data_out_10, data_out_11);
   input [1:0] selector;
   input       data_in;
   output      data_out_00;
   output      data_out_01;
   output      data_out_10;
   output      data_out_11;
   
   assign data_out_00 = (selector == 2'b00) ? data_in : 
                        1'b0;
   assign data_out_01 = (selector == 2'b01) ? data_in : 
                        1'b0;
   assign data_out_10 = (selector == 2'b10) ? data_in : 
                        1'b0;
   assign data_out_11 = (selector == 2'b11) ? data_in : 
                        1'b0;
   
endmodule
