//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Wed Mar 22 2017 21:01:38
//
//      Input file      : 
//      Component name  : multiplexer4
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module multiplexer4(selector, data_in_00, data_in_01, data_in_10, data_in_11, data_out);
   parameter      w = 0; //positive is treated as a variable
   input [1:0]    selector;
   input [w-1:0]  data_in_00;
   input [w-1:0]  data_in_01;
   input [w-1:0]  data_in_10;
   input [w-1:0]  data_in_11;
   output [w-1:0] data_out;
   
   assign data_out = (selector == 2'b00) ? data_in_00 : 
                     (selector == 2'b01) ? data_in_01 : 
                     (selector == 2'b10) ? data_in_10 : 
                     data_in_11;
   
endmodule
