//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Wed Mar 22 2017 21:08:19
//
//      Input file      : 
//      Component name  : selectunit
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module selectunit(data_in, k_in, data_out);
   input         data_in;
   input [31:0]  k_in;
   output [31:0] data_out;
   
   wire [0:0]    index;
   assign index = ((k_in < k)) ? k_in : 
                  0;
   assign data_out = data_in[index];
   
endmodule
