//--------------------------------------------------------------------------------------------
//
// Generated by X-HDL VHDL Translator - Version 2.0.0 Feb. 1, 2011
// Wed Mar 22 2017 20:45:09
//
//      Input file      : 
//      Component name  : vector_register
//      Author          : 
//      Company         : 
//
//      Description     : 
//
//
//--------------------------------------------------------------------------------------------


module vector_register(clk, r_in, v_out, w_out, load_r, load_select, k_in, select_v, select_w, select_r);
   parameter [8:0] n = 0;
   parameter       slicenr = 0; //may have some problems for generic
   
   input           clk;
   
   input [31:0]    r_in;
   
   output [31:0]   v_out;
   reg [31:0]      v_out;
   output [31:0]   w_out;
   reg [31:0]      w_out;
   
   input           load_r;
   input           load_select;
   input [31:0]    k_in;
   input [7:0]     select_v;
   input [3:0]     select_w;
   input [7:0]     select_r;
   
   reg [31:0]      regfile[0:n-1];
   
   always
   begin
      @(posedge clk);
      
      if ((load_r == 1'b1 & load_select != 1'b1) | (load_r == 1'b1 & load_select == 1'b1 & k_in == slicenr))
         regfile[select_r] <= r_in;
      
      v_out <= regfile[select_v];
      w_out <= regfile[select_w];
   end
   
endmodule


